[build]
  command = "bun run build"
  publish = ".svelte-kit/output/client"
  functions = ".svelte-kit/output/server"

[build.environment]
  BUN_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200 